version: '3.8'

services:

    depends_on:
      - backend
    networks:
      - flavorsnap-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  flavorsnap-network:
    driver: bridge

